import Head from "next/head";
import Post from "../components/Post";
import styles from "../styles/Home.module.css";
const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((item, index) => (
        <Post key={index} item={item} />
      ))}
    </div>
  );
}

export async function getStaticProps(context) {
  const file = fs.readdirSync(path.join("posts"));
  const posts = file.map((filename) => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data } = matter(markdownWithMeta);
    return {
      slug,
      data,
    };
  });
  return {
    props: {
      posts: posts,
    },
  };
}
