import Head from "next/head";
import styles from "../styles/Home.module.css";
const fs = require("fs");
const path = require("path");
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      the blog page {posts}
    </div>
  );
}

export async function getStaticProps(context) {
  const file = fs.readdirSync(path.join("posts"));
  console.log(file);
  return {
    props: {
      posts: "hello world",
    },
  };
}
