import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        {`
          .demo {
            color: red;
          }
          .myImg {
            border-radius: 10px;
          }
        `}
      </style>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <p className="demo">code war</p>
        </h1>
        <div>
          <img
            className="myImg"
            src="/unsplashImage.jpg"
            alt="unsplash image"
            height="426px"
            width="640px"
          ></img>
        </div>
        <p className={styles.description}>a popular blog site</p>
      </main>
    </div>
  );
}
