import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        {`
          .demo {
            color: red;
          }
          .myImg {
            border-radius: 10px;
          }
        `}
      </style>
      <nav className={styles.nav}>
        <ul>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href="/blog">
            <a>Blog</a>
          </Link>
          <Link href="/about">
            <a>About</a>
          </Link>
          <Link href="/contact">
            <a>Contact</a>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <p className="demo">code war</p>
        </h1>
        <div>
          <Image
            className="myImg"
            src="/unsplashImage.jpg"
            alt="unsplash image"
            height="426px"
            width="640px"
          ></Image>
        </div>
        <p className={styles.description}>a popular blog site</p>
      </main>
    </div>
  );
}
