import matter from 'gray-matter'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
const fs = require("fs")
const path = require("path")
export default function Home(props) {
  console.log(props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

export async function getStaticProps(){
  const files = fs.readdirSync(path.join('posts'))
  const file = files.map(filename => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8');
    const {data} = matter(markdownWithMeta)
    return {
      slug,
      data
    }
  })
  return { 
    props: {
      file
    }
  }
}